#include "counter.hpp"

/*
A signal is emitted when a particular event occurs, Signals are emitted by an
object when its internal state has changed in some way. Qt's widgets have many
predefined signals, but we can always subclass widgets to add our own signal


connect(object1, signal1, object2, slot3)

A slot is a function that is called in response to a particular signal. Qt's
widgets have many pre-defined slots

The signature of a signal must match the signature of the receiving slot

A class which emits a signal neither knows nor cares which slots receive the
signal.

All classes that inherit from QObject or one of its subclasses (e.g., QWidget)
can contain signals and slots. It does not know or care whether anything is
receiving the signals it emits.

Slots can be used for receiving signals, but they are also normal member
functions.

connect a signal directly to another signal. (This will emit the second signal
immediately whenever the first is emitted.)

Execution of the code following the emit statement will occur once all slots
have returned.

Signals are automatically generated by the moc (Meta-Object Compiler ) and must
not be implemented in the .cpp file. They can never have return types (i.e. use
void).


Slots are normal C++ functions, as slots, they can be invoked by any component,
regardless of its access level, via a signal-slot connection. This means that a
signal emitted from an instance of an arbitrary class can cause a private slot
to be invoked in an instance of an unrelated class.


*/

int main() {
  Counter a, b;
  QObject::connect(&a, &Counter::valueChanged, &b, &Counter::valueNotification);

  a.setValue(2);
  // std::cout << b.value() << std::endl;
}
